"""Abstract base class for FluidGym environments."""

import gc
import logging
import weakref
from abc import ABC, abstractmethod
from collections.abc import Callable, Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any, NamedTuple

import numpy as np
import pandas as pd
import seaborn as sns
import torch
from gymnasium import spaces
from phipict import _C, Hooks
from phipict.io.domain_io import load_domain, save_domain
from phipict.io.output import _resample_block_data, plot_grids
from phipict.simulation.simulation import Simulation
from phipict.solvers.tolerance import SolverTolerance, parse_tolerance

from fluidgym._palette import DEFAULT_PALETTE
from fluidgym.config import config as fluidgym_config
from fluidgym.envs.util.visualization import MultiblockResampler, slice_plane_axes
from fluidgym.logging import get_logger
from fluidgym.types import EnvMode, FluidEnvLike
from fluidgym.util.data_utils import (
    load_statistics,
    load_uncontrolled_episode,
    prepare_initial_domains,
    save_statistics,
    save_uncontrolled_episode,
)


class Stats(NamedTuple):
    """Statistical summary of a quantity."""

    mean: float
    min: float
    max: float
    p5: float
    p25: float
    p50: float
    p75: float
    p95: float


@dataclass
class EnvState:
    """Dataclass to hold the state of a FluidEnv environment."""

    class_name: str
    domain: _C.Domain
    n_steps: int
    mode: EnvMode
    additional_info: dict[str, Any]


# Number of domains per mode
N_INITIAL_DOMAINS = 10

# Seeds used when the simulation needs to be restarted for every domain
MODE_SEEDS = [100, 200, 300]


class FluidEnv(ABC, FluidEnvLike):
    """Abstract base class for FluidGym environments.

    It provides common functionality for all FluidGym environments,
    such as managing the simulation, rendering, and saving/loading initial domains.

    **Batched environments.** With ``n_envs=E`` the environment runs E copies of
    itself in one batched simulation on its GPU: same grid, boundaries and
    sparsity patterns, own states, actions, observations and rewards. The API then
    carries a leading env dim everywhere: actions ``[E, *action]``
    (``[E, A, *action]`` in MARL), observations ``[E, *obs]``, rewards ``[E]``
    (``[E, A]``), ``terminated`` and
    ``truncated`` bool tensors ``[E]`` and info values ``[E]``. With the default
    ``n_envs=None`` it is a single environment without that dim, exactly as
    before. All environments share the episode length and, with adaptive
    substepping, the time step (set by the fastest environment).

    Internally, every environment works with the leading env dim regardless of
    ``n_envs`` (``E = 1`` for a single environment): block fields are ``[E, ...]``
    and :meth:`_apply_action`, :meth:`_get_global_obs`, :meth:`_advance_impl` and
    :meth:`_finish_step` take and return per-environment tensors. The base class
    removes the env dim for a single environment.

    Raises
    ------
    RuntimeError
        If CUDA is not available.

    ValueError
        If ndims is not 2 or 3.

    Notes
    -----
    The environment must be reset before calling step().
    The initial domain must be generated by calling init() before using the environment
    for training or evaluation.
    The initial domain is saved to disk when init() is called, and loaded when reset()
    is called.
    """

    metadata = {"render_modes": ["rbg_array"], "render_fps": 24}

    _default_render_key: str

    _ndims: int
    _supports_marl: bool = False

    _domain: _C.Domain
    _sim: Simulation
    _dtype: torch.dtype
    _cuda_device: torch.device
    _cpu_device: torch.device
    _differentiable: bool

    # Solver settings shared by every env, see ``_resolve_pressure_tol`` and
    # ``_resolve_advection_tol``
    _advection_tol: float | SolverTolerance | None
    _pressure_tol: float | SolverTolerance | None
    _pressure_tol_intermediate: float | SolverTolerance | None
    _pressure_warm_start: bool

    # Overrides applied to every simulation this env builds, see
    # ``_apply_solver_overrides``. None leaves the concrete env's own choice alone
    _linear_solve_max_iter: int | None
    _exclude_advection_solve_gradients: bool | None
    _exclude_pressure_solve_gradients: bool | None
    _exclude_pressure_gradient_adjoint: bool | None

    # Checkpoint each env step for differentiable BPTT. See ``bptt_checkpoint``
    _bptt_checkpoint: bool = False

    # Relative residual of the adjoint linear solves; None = inherit the forward's.
    # See ``adjoint_rtol``
    _adjoint_rtol: float | None = None

    # PISO steps per checkpoint segment; 0 = one segment per env step. See
    # ``bptt_segment_size``. Every env can be cut mid-step, a step is
    # ``_advance_impl`` + ``_finish_step``, so this is a memory/carry trade-off
    # rather than a capability question
    _bptt_segment_size: int = 0

    # What ``bptt_segment_size`` starts at, and what setting it to None asks for.
    # None leaves the env step whole, which is what the 2D envs want: their replay
    # tape fits, and a whole step is the cheapest carry. The 3D envs override it
    # with a segment their tape fits in. See ``default_bptt_segment_size``
    _default_bptt_segment_size: int | None = None

    # Where checkpoint carries live between forward and backward: a device, or a
    # directory when ``_bptt_carry_spill_dir`` is set
    _bptt_offload_device: torch.device | None = torch.device("cpu")
    _bptt_carry_spill_dir: str | None = None
    _bptt_spill_root: str | None = None
    # Deletes ``_bptt_spill_root`` when this env is collected or the process exits,
    # so a run does not leave its carries on disk. See ``close``
    _bptt_spill_finalizer: weakref.finalize | None = None

    _seed: int | None = None

    _reset_called: bool = False
    __resampler: MultiblockResampler | None = None
    # (id(coords), id(out_indices)) -> DiffMultiblockResampler. See
    # `_diff_resampler`; instance-level, assigned in __init__
    __diff_resamplers: dict

    # Axes ("x", "y", "z") to mirror when rendering a plane, so that an env whose
    # domain is set up in an orientation that does not plot well can be shown the
    # way it is read. Only affects rendering, never observations
    _render_mirror_axes: tuple[str, ...] = ()

    _render_resolution: int = 1
    # The environment of a batch that render() shows, see _render_env_data
    _render_env_idx: int = 0
    # Index of this env's first environment in a larger vector env (the envs of
    # the workers of a ParallelFluidEnv), for the names of rendered frames
    _env_index_offset: int = 0
    _n_episodes: int = 0
    _n_steps: int = 0
    __load_domain_on_reset: bool
    _step_length: float
    _dt: float

    # PRNGs
    _torch_rng_cuda: torch.Generator
    _torch_rng_cpu: torch.Generator
    _np_rng: np.random.Generator

    # How long the simulation needs to be run
    # to reach a steady state before starting RL
    _initial_domain_steps: int

    # Whether the simulations needs to be
    # restarted for every domain
    _initial_domain_restart: bool

    _mode: EnvMode = EnvMode.TRAIN

    _metrics: list[str]
    _metrics_stats: dict[str, Stats] = {}
    _velocity_stats: Stats | None = None
    _pressure_stats: Stats | None = None

    # DataFrames containing uncontrolled episode metrics for the currently loaded
    # (non-randomized) initial domain of every environment
    _uncontrolled_episodes: list[pd.DataFrame | None] = []

    def __init__(
        self,
        adaptive_cfl: float,
        dt: float,
        step_length: float,
        episode_length: int,
        ndims: int,
        use_marl: bool,
        dtype: torch.dtype = torch.float32,
        cuda_device: torch.device | None = None,
        cpu_device: torch.device | None = None,
        load_initial_domain: bool = True,
        load_domain_statistics: bool = True,
        randomize_initial_state: bool = True,
        enable_actions: bool = True,
        differentiable: bool = False,
        advection_tol: float | SolverTolerance | Mapping[str, float] | None = None,
        pressure_tol: float | SolverTolerance | Mapping[str, float] | None = None,
        pressure_tol_intermediate: (
            float | SolverTolerance | Mapping[str, float] | None
        ) = None,
        pressure_warm_start: bool = False,
        linear_solve_max_iter: int | None = None,
        exclude_advection_solve_gradients: bool | None = None,
        exclude_pressure_solve_gradients: bool | None = None,
        exclude_pressure_gradient_adjoint: bool | None = None,
        n_envs: int | None = None,
    ):
        """Initialize the FluidEnv.

        Parameters
        ----------
        adaptive_cfl: float
            Target CFL number for adaptive time stepping.

        dt: float
            The simulation time step.

        step_length: float
            The length of each environment step in non-dimensional time units.

        episode_length: int
            The number of steps per episode.

        ndims: int
            The number of spatial dimensions (2 or 3).

        use_marl: bool
            Whether to use multi-agent reinforcement learning (MARL) mode. If False,
            single-agent reinforcement learning (SARL) mode is used.

        dtype: torch.dtype
            The data type for the simulation (torch.float32 or torch.float64). Defaults
            to torch.float32.

        cuda_device: torch.device | None
            The CUDA device to use for the simulation. If None, the default CUDA device
            is used. Defaults to None.

        cpu_device: torch.device
            The CPU device to use for the simulation. If None, the default CPU device is
            used. Defaults to None.

        load_initial_domain: bool
            Whether to load the initial domain from disk. If False, a new domain will be
            created. Defaults to True.

        randomize_initial_state: bool
            Whether to randomize the initial state of the environment after loading or
            creating the domain. Defaults to False.

        enable_actions: bool
            Whether to enable actions. This should be False when generating initial
            domains. Defaults to True.

        differentiable: bool
            Whether to enable differentiable simulation. Defaults to False.

        advection_tol: float | SolverTolerance | Mapping[str, float] | None
            Tolerance for the momentum and passive-scalar advection solves; same
            forms as ``pressure_tol``. None (the default) keeps the tolerance the
            concrete environment picked for itself, see
            :meth:`_resolve_advection_tol`.

        pressure_tol: float | SolverTolerance | Mapping[str, float] | None
            Tolerance for the pressure solve. A float is an absolute tolerance on
            ``||r||_2/sqrt(n)``, a
            :class:`~phipict.solvers.tolerance.SolverTolerance` (or a
            mapping with ``rtol``/``atol``) specifies it relative to the RHS. None
            (the default) keeps the tolerance the concrete environment picked for
            itself, see :meth:`_resolve_pressure_tol`.

        pressure_tol_intermediate: float | SolverTolerance | Mapping | None
            Tolerance for every pressure solve that is not the final corrector.
            Only the final corrector's pressure survives into the solution, so the
            earlier ones can be solved loosely. None (the default) applies
            ``pressure_tol`` everywhere.

        pressure_warm_start: bool
            Seed each pressure solve with the previous sub-step's result for the
            same corrector index instead of with zero. An initial guess cannot
            change the converged answer, only the iteration count. Defaults to
            False.

        linear_solve_max_iter: int | None
            Iteration limit for the advection and pressure solves. None (the
            default) leaves the simulation's own limit in place. A differentiable
            run may need more than an evaluation run does: the adjoint solve is
            held to the forward's *relative* accuracy, which on an adjoint RHS far
            below the forward's is a tighter absolute target than the forward ever
            had to meet.

        exclude_advection_solve_gradients: bool | None
            Drop the gradient of the advection solve, i.e. treat its result as a
            constant in the backward. Diagnostic only, meaning it removes a real term of
            the adjoint. None (the default) leaves the simulation's own setting.

        exclude_pressure_solve_gradients: bool | None
            The same for the pressure solve. Diagnostic only. None (the default)
            leaves the simulation's own setting.

        exclude_pressure_gradient_adjoint: bool | None
            Cut the pressure path out of the PISO velocity-correction backward.

        n_envs: int | None
            Number of environments simulated together in one batched simulation.
            An int switches to the vectorized API with a leading env dim on all
            actions, observations, rewards, flags and infos (also for 1). None (the
            default) is a single environment without that dim.
        """
        super().__init__()

        if n_envs is not None and int(n_envs) < 1:
            raise ValueError(f"n_envs must be at least 1, got {n_envs}.")
        self._vectorized = n_envs is not None
        self._n_envs = 1 if n_envs is None else int(n_envs)

        if not torch.cuda.is_available():
            raise RuntimeError("CUDA is not available. FluidGym requires a CUDA GPU.")

        if ndims not in [2, 3]:
            raise ValueError("ndims must be 2 or 3.")
        self._ndims = ndims

        self._dt = dt
        self._adaptive_cfl = adaptive_cfl
        self._step_length = step_length
        self._episode_length = episode_length

        self._use_marl = use_marl
        if self._use_marl and not self._supports_marl:
            raise ValueError("This env does not support multi-agent mode.")

        # Needs ``_dt`` / ``_step_length``, which fix the PISO steps of an env step
        self._bptt_segment_size = self._resolve_bptt_segment_size(None)

        self._cuda_device = torch.device("cuda") if cuda_device is None else cuda_device
        self._cpu_device = torch.device("cpu") if cpu_device is None else cpu_device
        self._dtype = dtype
        self.__load_domain_on_reset = load_initial_domain
        self._randomize_initial_state = randomize_initial_state
        self._enable_actions = enable_actions
        self._differentiable = differentiable
        self.__diff_resamplers = {}

        self._advection_tol = parse_tolerance(advection_tol)
        self._pressure_tol = parse_tolerance(pressure_tol)
        self._pressure_tol_intermediate = parse_tolerance(pressure_tol_intermediate)
        self._pressure_warm_start = bool(pressure_warm_start)

        self._linear_solve_max_iter = (
            None if linear_solve_max_iter is None else int(linear_solve_max_iter)
        )
        self._exclude_advection_solve_gradients = exclude_advection_solve_gradients
        self._exclude_pressure_solve_gradients = exclude_pressure_solve_gradients
        self._exclude_pressure_gradient_adjoint = exclude_pressure_gradient_adjoint

        if load_initial_domain or load_domain_statistics:
            prepare_initial_domains(initial_domain_id=self.initial_domain_id)

        if load_domain_statistics:
            self._load_domain_statistics()
        else:
            self._logger.warning(
                "Domain statistics not loaded. Some environment features may be "
                "unavailable. Only use this option for debugging or development "
                "purposes."
            )

        self._action_space = self._get_action_space()
        self._observation_space = self._get_observation_space()

        if self._use_marl:
            action_shape = (self.n_agents, *self.action_space.shape)
        else:
            action_shape = self.action_space.shape
        # What the env implementations act with: always with the env dim
        self._batched_zero_action = torch.zeros(
            (self._n_envs, *action_shape),
            device=self._cuda_device,
            dtype=self._dtype,
            requires_grad=False,
        )
        # What the public API takes: without the env dim for a single environment
        self._zero_action = (
            self._batched_zero_action
            if self._vectorized
            else self._batched_zero_action[0]
        )

    @abstractmethod
    def _get_action_space(self) -> spaces.Box:
        """Per-agent action space."""
        raise NotImplementedError

    @abstractmethod
    def _get_observation_space(self) -> spaces.Dict:
        """Per-agent observation space."""
        raise NotImplementedError

    @property
    def _logger(self) -> logging.Logger:
        """Logger for the environment."""
        return get_logger(f"envs.{self.__class__.__name__}")

    @property
    def use_marl(self) -> bool:
        """Whether the environment is in multi-agent reinforcement learning mode."""
        return self._use_marl

    @property
    def n_envs(self) -> int:
        """Number of environments simulated together (1 for a single one)."""
        return self._n_envs

    @property
    def num_envs(self) -> int:
        """Alias of :attr:`n_envs`, the name vectorized-env libraries use."""
        return self._n_envs

    @property
    def vectorized(self) -> bool:
        """Whether the API carries a leading env dim (``n_envs`` was given)."""
        return self._vectorized

    @staticmethod
    def _per_env_sum(values: torch.Tensor) -> torch.Tensor:
        """Sum over everything but the leading env dim: ``[E, ...] -> [E]``.

        A single environment is reduced as one sum over all elements, exactly as
        before batching existed.
        """
        if values.size(0) == 1:
            return values.sum().reshape(1)
        return values.reshape(values.size(0), -1).sum(dim=1)

    @staticmethod
    def _per_env_mean(values: torch.Tensor) -> torch.Tensor:
        """Mean over everything but the leading env dim: ``[E, ...] -> [E]``."""
        if values.size(0) == 1:
            return values.mean().reshape(1)
        return values.reshape(values.size(0), -1).mean(dim=1)

    @staticmethod
    def _env_broadcast(values: torch.Tensor, like: torch.Tensor) -> torch.Tensor:
        """Per-environment ``values`` ``[E, ...]`` shaped to broadcast against ``like``.

        E.g. one action per environment scaling a boundary profile
        ``[1 or E, C, *face]``: ``profile * _env_broadcast(action, profile)``.
        """
        return values.reshape(values.size(0), *[1] * (like.dim() - 1))

    def _to_batched(self, action: torch.Tensor) -> torch.Tensor:
        """A public action as the env implementations take it (with the env dim)."""
        return action if self._vectorized else action.unsqueeze(0)

    def _from_batched(self, value: Any) -> Any:
        """A per-environment result as the public API returns it.

        Tensors and (nested) mappings of tensors lose the env dim for a single
        environment; anything else is returned as is.
        """
        if self._vectorized:
            return value
        if isinstance(value, Mapping):
            return {key: self._from_batched(item) for key, item in value.items()}
        if torch.is_tensor(value) and value.dim() > 0:
            return value[0]
        return value

    @property
    @abstractmethod
    def n_agents(self) -> int:
        """The number of agents in the environment."""
        raise NotImplementedError

    @property
    def step_length(self) -> float:
        """The length of each environment step in non-dimensional time units."""
        return self._step_length

    @property
    def episode_length(self) -> int:
        """The number of steps per episode."""
        return self._episode_length

    @property
    def dt(self) -> float:
        """The simulation time step."""
        return self._dt

    @property
    def ndims(self) -> int:
        """The number of spatial dimensions (2 or 3)."""
        return self._ndims

    @property
    @abstractmethod
    def obs_resampling_shape(self) -> tuple[int, ...]:
        """The shape of the uniform grid the observations are resampled onto.

        This is a property of the environment and does not change: the
        observations, and the sensor and mask indices that go with them, are
        defined on this grid. To render at a higher resolution, set
        :attr:`render_resolution`.
        """
        raise NotImplementedError

    @property
    def render_resolution(self) -> int:
        """How much finer the render grid is than ``obs_resampling_shape``.

        A multiplier of 1, the default, renders on the observation grid. Raising
        it only affects rendering, never the observations.
        """
        return self._render_resolution

    @render_resolution.setter
    def render_resolution(self, render_resolution: int) -> None:
        if not isinstance(render_resolution, (int, np.integer)):
            raise TypeError(
                f"render_resolution must be an int, got {type(render_resolution)}"
            )
        if render_resolution < 1:
            raise ValueError(
                f"render_resolution must be at least 1, got {render_resolution}"
            )

        if render_resolution != self._render_resolution:
            self._render_resolution = int(render_resolution)
            # The resampler is built for a fixed render grid
            self.__resampler = None

    @property
    def render_shape(self) -> tuple[int, ...]:
        """The shape of the rendered domain.

        This is ``obs_resampling_shape`` scaled by :attr:`render_resolution`, and
        is used for rendering only.
        """
        return tuple(n * self.render_resolution for n in self.obs_resampling_shape)

    @property
    def metrics(self) -> list[str]:
        """The list of metrics tracked by the environment."""
        return self._metrics

    @property
    def time_passed(self) -> float:
        """The total time passed in the current episode."""
        return self._n_steps * self._step_length

    @property
    def n_sim_steps(self) -> int:
        """The number of simulation steps per environment step."""
        return self._n_sim_steps

    @property
    def mode(self) -> EnvMode:
        """The current mode of the environment ('train', 'val', or 'test')."""
        return self._mode

    @mode.setter
    def mode(self, mode: EnvMode) -> None:
        if mode not in [EnvMode.TRAIN, EnvMode.VAL, EnvMode.TEST]:
            raise ValueError("mode must be 'train', 'val', or 'test'.")
        self._mode = mode

    @property
    def cuda_device(self) -> torch.device:
        """The CUDA device used by the environment."""
        return self._cuda_device

    @property
    def differentiable(self) -> bool:
        """Whether the environment is differentiable."""
        return self._differentiable

    @property
    def bptt_checkpoint(self) -> bool:
        """Run each env step as an activation checkpoint (differentiable BPTT).

        The step is run under ``no_grad`` during the rollout and replayed under
        ``enable_grad`` in backward, so only one step's activations are ever live.
        This is what makes GPU peak independent of the rollout length; offloading
        the tape alone leaves a residue per PISO step that caps the horizon.

        Costs one extra forward per step, plus one carry per step (see
        ``bptt_offload_device`` / ``bptt_carry_spill_dir``). Only meaningful on a
        differentiable environment.
        """
        return self._bptt_checkpoint

    @bptt_checkpoint.setter
    def bptt_checkpoint(self, value: bool) -> None:
        value = bool(value)
        if value and not self._differentiable:
            raise RuntimeError(
                "Activation checkpointing only applies to a differentiable "
                "environment (construct with differentiable=True)."
            )
        self._bptt_checkpoint = value

    @property
    def adjoint_rtol(self) -> float | None:
        """Relative residual every adjoint (backward) linear solve is held to.

        Each adjoint solve stops on ``||r|| < rtol * ||g||``, with ``g`` its
        incoming gradient. The tolerance is proportional to ``g``, so the gradient
        does not depend on the scale of the loss: the reward scale, the natural
        magnitude of the reward or the adjoint decaying along the rollout. ``None``
        (the default) holds each adjoint solve to the
        ``rtol`` of its forward solve, e.g. ``pressure_tol``, and a forward solve
        with an absolute tolerance to
        :data:`phipict.solvers.tolerance.ADJOINT_RTOL_FALLBACK`. A float
        overrides this for every solve.

        This is a process-wide solver setting
        (:func:`phipict.solvers.tolerance.set_adjoint_rtol`), shared by every env
        in the process; the last one set wins.
        """
        return self._adjoint_rtol

    @adjoint_rtol.setter
    def adjoint_rtol(self, value: float | None) -> None:
        from phipict.solvers.tolerance import set_adjoint_rtol

        if value is not None:
            value = float(value)
            if not value > 0.0:
                raise ValueError(f"adjoint_rtol must be positive, got {value}.")
            if not self._differentiable:
                raise RuntimeError(
                    "adjoint_rtol only applies to a differentiable environment "
                    "(construct with differentiable=True)."
                )
        set_adjoint_rtol(value)
        self._adjoint_rtol = value

    @property
    def default_bptt_segment_size(self) -> int:
        """The ``bptt_segment_size`` this env starts at, as it resolves it.

        ``0`` for an env that leaves its step whole; otherwise a divisor of
        ``n_sim_steps``.
        """
        return self._resolve_bptt_segment_size(None)

    def _resolve_bptt_segment_size(self, value: int | None) -> int:
        """Turn a requested checkpoint segment into PISO steps of one env step.

        ``None`` asks for this env's own :attr:`default_bptt_segment_size`; ``0``,
        or anything at or above ``n_sim_steps``, is one segment per env step.
        Anything else is snapped down to the nearest divisor of ``n_sim_steps``,
        so that every segment of a step is the same length.

        Parameters
        ----------
        value: int | None
            The requested number of PISO steps per segment, or None for this
            env's default.

        Returns
        -------
        int
            PISO steps per segment: 0, or a divisor of ``n_sim_steps``.
        """
        if value is None:
            value = self._default_bptt_segment_size or 0

        size = max(0, int(value))
        total = self._n_sim_steps
        if size == 0 or size >= total:
            return 0

        snapped = next(n for n in range(size, 0, -1) if total % n == 0)
        if snapped != size:
            self._logger.warning(
                "bptt_segment_size %d does not divide the %d PISO steps of an env "
                "step; using %d instead.",
                size,
                total,
                snapped,
            )
        return snapped

    @property
    def bptt_segment_size(self) -> int:
        """PISO steps per checkpoint segment (0 = one segment per env step)."""
        return self._bptt_segment_size

    @bptt_segment_size.setter
    def bptt_segment_size(self, value: int | None) -> None:
        self._bptt_segment_size = self._resolve_bptt_segment_size(value)

    @property
    def bptt_offload_device(self) -> torch.device | None:
        """Where checkpoint carries are parked (``None`` = keep on the GPU)."""
        return self._bptt_offload_device

    @bptt_offload_device.setter
    def bptt_offload_device(self, value: torch.device | str | None) -> None:
        self._bptt_offload_device = None if value is None else torch.device(value)

    @property
    def bptt_carry_spill_dir(self) -> str | None:
        """Directory to write checkpoint carries into, instead of host RAM.

        At a long horizon the carry is what host memory runs out of: it is one
        state snapshot per step. Note ``/tmp`` and ``/dev/shm`` are usually
        tmpfs, i.e. RAM.
        """
        return self._bptt_carry_spill_dir

    @bptt_carry_spill_dir.setter
    def bptt_carry_spill_dir(self, value: str | None) -> None:
        self._bptt_carry_spill_dir = None if value is None else str(value)
        # The next checkpointed step allocates a root under the new directory; the
        # old one is finished with
        self._release_spill_root()

    def _attr_accessor(self, name: str) -> Any:
        """Accessor for an env attribute that is carried across steps.

        ``name`` is the real attribute name, so a private one has to be given
        name-mangled (``"_MyEnv__last_control"``).
        """
        return (lambda: getattr(self, name), lambda t: setattr(self, name, t))

    def _checkpoint_accessors(self) -> list[Any]:
        """``(getter, setter)`` pairs defining the BPTT checkpoint carry.

        Covers the generic domain solver state. An env whose step reads and
        writes state outside the ``Domain`` (a lagged term, a smoothed control)
        must extend this as ``super()._checkpoint_accessors() + [...]``, or the
        checkpoint replay will not reproduce the rollout.
        """
        from fluidgym.envs.checkpointing import default_domain_accessors

        sim, domain = self._sim, self._sim.domain
        assert domain is not None

        return default_domain_accessors(domain) + [
            # Warm-start state: cross-step, and not part of the Domain
            (lambda: domain.velocityResult, domain.setVelocityResult),
            (lambda: domain.pressureResult, domain.setPressureResult),
            (
                lambda: sim.pressure_guess_state,
                lambda t: setattr(sim, "pressure_guess_state", t),
            ),
        ]

    def _release_spill_root(self) -> None:
        """Delete this env's carry spill directory, if it has one."""
        if self._bptt_spill_finalizer is not None:
            self._bptt_spill_finalizer()  # idempotent: a no-op once it has run
            self._bptt_spill_finalizer = None
        self._bptt_spill_root = None

    def close(self) -> None:
        """Release what this env holds outside Python: the carry spill directory.

        Also runs on garbage collection and at interpreter exit via the finalizer,
        so a run that never calls this still cleans up after itself; only a killed
        process leaves files behind, and the next run sweeps those.
        """
        self._release_spill_root()

    def _checkpointed_step(self, action: torch.Tensor, step_fn: Any) -> Any:
        """Run one env step as an activation checkpoint."""
        from fluidgym.envs.checkpointing import (
            checkpointed_step,
            cleanup_carry_spill_dir,
            make_carry_spill_dir,
        )

        if self._bptt_carry_spill_dir is not None and self._bptt_spill_root is None:
            self._bptt_spill_root = make_carry_spill_dir(self._bptt_carry_spill_dir)
            self._bptt_spill_finalizer = weakref.finalize(
                self, cleanup_carry_spill_dir, self._bptt_spill_root
            )

        domain = self._sim.domain
        assert domain is not None

        # Bind the segment to the simulation it is recorded on, not to whatever
        # ``self._sim`` happens to be when backward replays it
        bind = self._episode_binding()
        accessors = [
            (bind(getter), bind(setter))
            for getter, setter in self._checkpoint_accessors()
        ]

        return checkpointed_step(
            accessors,
            bind(step_fn),
            grad_inputs=(action,),
            on_restored=domain.UpdateDomainData,
            release_fn=domain.DetachFwd,
            offload_device=self._bptt_offload_device,
            spill_dir=self._bptt_spill_root,
        )

    def _episode_binding(self) -> Callable[[Callable[..., Any]], Callable[..., Any]]:
        """Wrap callables so they run against *this* episode's simulation.

        :meth:`reset` builds a new ``Domain`` and ``Simulation`` and rebinds every
        attribute derived from them, and the auto-reset of a finished episode
        happens inside the last step of a rollout, before the rollout's backward
        pass runs.
        """
        episode = dict(self.__dict__)

        def holds_this_episode() -> bool:
            """Whether the env is still on the simulation this was bound to."""
            live = self.__dict__
            return live is episode or (
                live.get("_sim") is episode.get("_sim")
                and live.get("_domain") is episode.get("_domain")
            )

        def bind(fn: Callable[..., Any]) -> Callable[..., Any]:
            # Deliberately not ``functools.wraps``: several setters are pybind11
            # bound methods, which have no ``__dict__`` to copy
            def bound(*args: Any, **kwargs: Any) -> Any:
                # Also the re-entrant case: a bound accessor called from inside a
                # bound step already runs on ``episode``
                if holds_this_episode():
                    return fn(*args, **kwargs)

                live = self.__dict__
                self.__dict__ = episode
                try:
                    return fn(*args, **kwargs)
                finally:
                    self.__dict__ = live

            return bound

        return bind

    def _segment_sizes(self) -> list[int]:
        """PISO-step counts of the checkpoint segments of one env step."""
        total = self._n_sim_steps
        size = self._bptt_segment_size or total
        if size >= total:
            return [total]
        sizes = [size] * (total // size)
        if total % size:
            sizes.append(total % size)
        return sizes

    def _segmented_step(
        self, action: torch.Tensor
    ) -> tuple[dict[str, torch.Tensor], torch.Tensor, bool, dict[str, torch.Tensor]]:
        """Run one env step as several checkpoint segments of PISO steps.

        Each segment advances the simulation and hands back the metrics of the
        substeps it ran. The observation and the reward are computed once, from the
        concatenation of all of them and from the state the last segment leaves
        behind. That is what keeps the split exact: no per-segment quantity is
        averaged twice, and nothing in the reward has to be linear in the substeps.
        """
        parts = [
            self._checkpointed_step(action, lambda a, n=n: self._advance_impl(a, n))
            for n in self._segment_sizes()
        ]
        # Concatenated along the substep axis only: a metric measured per cell keeps
        # its own shape, so ``_finish_step`` sees exactly what an unsplit step's
        # ``_advance_impl`` would have handed it
        metrics = {
            key: torch.cat(
                [
                    part[key] if part[key].dim() else part[key].reshape(1)
                    for part in parts
                ]
            )
            for key in parts[0]
        }
        finish = self._finish_marl_step if self._use_marl else self._finish_step
        return finish(metrics)

    def train(self) -> None:
        """Set the environment to training mode."""
        self.mode = EnvMode.TRAIN

    def val(self) -> None:
        """Set the environment to evaluation mode."""
        self.mode = EnvMode.VAL

    def test(self) -> None:
        """Set the environment to test mode."""
        self.mode = EnvMode.TEST

    def sample_action(self) -> torch.Tensor:
        """Sample a random action uniformly from the action space.

        Returns
        -------
        torch.Tensor
            A random action.
        """
        if not isinstance(self.action_space, spaces.Box):
            raise TypeError("Only implemented for Box.")

        if self._seed is None:
            raise RuntimeError("Environment must be seeded before sampling actions.")

        low = torch.as_tensor(self.action_space.low, device=self._cuda_device)
        high = torch.as_tensor(self.action_space.high, device=self._cuda_device)
        r = torch.rand(
            self._zero_action.shape,
            device=self._cuda_device,
            generator=self._torch_rng_cuda,
        )
        return low + (high - low) * r

    @abstractmethod
    def _get_domain(self) -> _C.Domain:
        """Create and return the initial domain for the simulation.

        Returns
        -------
        _C.Domain
            The initial domain for the simulation.
        """
        raise NotImplementedError

    @abstractmethod
    def _get_hooks(self, domain: _C.Domain) -> Hooks:
        """Get the callbacks the simulation runs at its hooks.

        Parameters
        ----------
        domain: _C.Domain
            The domain for which to get the callbacks.

        Returns
        -------
        Hooks
            The callbacks per simulation hook.
        """
        raise NotImplementedError

    @abstractmethod
    def _get_simulation(
        self,
        domain: _C.Domain,
        hooks: Hooks,
    ) -> Simulation:
        """Create and return the simulation object.

        Parameters
        ----------
        domain: _C.Domain
            The domain for the simulation.

        hooks: Hooks
            The callbacks the simulation runs at its hooks.

        Returns
        -------
        Simulation
            The simulation object.
        """
        raise NotImplementedError

    def _resolve_pressure_tol(
        self, default: float | SolverTolerance | None
    ) -> float | SolverTolerance | None:
        """The configured pressure tolerance, or ``default`` if none was given.

        Concrete environments call this in ``_get_simulation`` with the tolerance
        they were tuned at, so that constructing them without ``pressure_tol``
        keeps exactly the accuracy they had before the kwarg existed.
        """
        return default if self._pressure_tol is None else self._pressure_tol

    def _resolve_advection_tol(
        self, default: float | SolverTolerance | None
    ) -> float | SolverTolerance | None:
        """The configured advection tolerance, or ``default`` if none was given.

        The counterpart of :meth:`_resolve_pressure_tol` for the momentum and
        passive-scalar solves. ``default`` is what the concrete environment was
        tuned at, so constructing it without ``advection_tol`` keeps exactly the
        accuracy it had before the kwarg existed, including ``None``, which
        leaves the solver on its dtype default.
        """
        return default if self._advection_tol is None else self._advection_tol

    def _resolve_linear_solve_max_iter(self, default: int) -> int:
        """The configured iteration limit, or ``default`` if none was given.

        Only for an environment that needs the number itself in
        ``_get_simulation``. The limit is applied to the simulation by
        :meth:`_apply_solver_overrides` either way.
        """
        if self._linear_solve_max_iter is None:
            return default
        return self._linear_solve_max_iter

    def _build_simulation(
        self,
        domain: _C.Domain,
        hooks: Hooks,
    ) -> Simulation:
        """Build the simulation and apply the env-level solver overrides to it.

        The single place a simulation is created, so an override given to the
        constructor reaches every simulation this env builds: the one from
        ``init``, the one a loaded domain gets, and the one ``set_state``
        rebuilds.
        """
        sim = self._get_simulation(domain, hooks)
        self._apply_solver_overrides(sim)
        return sim

    def _apply_solver_overrides(self, sim: Simulation) -> None:
        """Apply the constructor's solver overrides to a freshly built simulation.

        Every override is ``None`` by default and is then left alone, so an
        environment that sets one of these itself in ``_get_simulation`` keeps
        exactly what it set.
        """
        if self._linear_solve_max_iter is not None:
            sim.linear_solve_max_iterations = self._linear_solve_max_iter
        if self._exclude_advection_solve_gradients is not None:
            sim.exclude_advection_solve_gradients = (
                self._exclude_advection_solve_gradients
            )
        if self._exclude_pressure_solve_gradients is not None:
            sim.exclude_pressure_solve_gradients = (
                self._exclude_pressure_solve_gradients
            )
        if self._exclude_pressure_gradient_adjoint is not None:
            sim.exclude_pressure_gradient_adjoint = (
                self._exclude_pressure_gradient_adjoint
            )

    def _additional_initialization(self) -> None:
        """Perform any additional initialization after the domain and simulation are
        created.
        """
        raise NotImplementedError

    @abstractmethod
    def _apply_action(self, action: torch.Tensor) -> None:
        """Apply the given action to the simulation.

        Parameters
        ----------
        action: torch.Tensor
            The action to apply.
        """
        raise NotImplementedError

    @abstractmethod
    def _get_global_obs(self) -> dict[str, torch.Tensor]:
        """Return the current global observation.

        Returns
        -------
        dict[str, torch.Tensor]
            The current observation.
        """
        raise NotImplementedError

    def _get_local_obs(self) -> dict[str, torch.Tensor]:
        """Return the current local agent observations.

        Returns
        -------
        dict[str, torch.Tensor]
            The current local agent observations.
        """
        raise NotImplementedError

    @abstractmethod
    def _randomize_domain(self) -> None:
        """Randomize the current domain of the environment."""
        raise NotImplementedError

    def _check_initial_domains_exists(
        self, mode: EnvMode | None = None, idx: int | None = None
    ) -> bool:
        """Check if the initial domain exists on disk.

        Parameters
        ----------
        mode: EnvMode | None
            Environment mode (e.g., 'train', 'val', 'test'). If None, checks for all
            tags. Defaults to None.

        idx: int | None
            Index of the initial domain to check. If None, checks for all indices.
              to None.

        Returns
        -------
        bool
            True if the initial domain exists, False otherwise.
        """
        modes = [EnvMode.TRAIN, EnvMode.VAL, EnvMode.TEST] if mode is None else [mode]
        idxs = range(N_INITIAL_DOMAINS) if idx is None else [idx]

        try:
            for _idx in idxs:
                for _mode in modes:
                    self._load_initial_domain(mode=_mode, idx=_idx)
            return True
        except FileNotFoundError:
            return False

    def _initial_domain_indices(
        self, randomize: bool, domain_idx: int | Sequence[int] | None
    ) -> list[int]:
        """The initial domain of every environment.

        ``domain_idx`` is one index for all environments or one per environment.
        Without it, every environment draws its own index when randomizing, and
        all start from the first initial domain otherwise. A single environment
        draws exactly as it did before batching existed.
        """
        if domain_idx is None:
            if randomize:
                return [
                    int(self._np_rng.integers(0, N_INITIAL_DOMAINS))
                    for _ in range(self._n_envs)
                ]
            return [0] * self._n_envs
        if isinstance(domain_idx, (int, np.integer)):
            return [int(domain_idx)] * self._n_envs
        idxs = [int(i) for i in domain_idx]
        if len(idxs) != self._n_envs:
            raise ValueError(
                f"Expected one domain index per environment ({self._n_envs}), got "
                f"{len(idxs)}."
            )
        return idxs

    def _batch_domain(self, domain: _C.Domain) -> _C.Domain:
        """Turn a single-environment domain into one of ``n_envs`` copies of it."""
        if self._n_envs > 1:
            domain.setBatchSize(self._n_envs)
            domain.PrepareSolve()
        return domain

    def _load_initial_domains(self, mode: EnvMode, idxs: list[int]) -> _C.Domain:
        """Load the initial domain of every environment into one batched domain.

        Every distinct index is read from disk once: the batched domain starts as
        ``n_envs`` copies of the first environment's domain, and the environments
        with another index get its state copied in.
        """
        from phipict.batching import copy_env_state

        domain = self._batch_domain(self._load_initial_domain(mode=mode, idx=idxs[0]))
        for idx in dict.fromkeys(idxs):
            if idx == idxs[0]:
                continue
            src = self._load_initial_domain(mode=mode, idx=idx)
            for env_idx, env_domain_idx in enumerate(idxs):
                if env_domain_idx == idx:
                    copy_env_state(domain, env_idx, src)
        return domain

    def _set_initial_state(
        self,
        randomize: bool | None = None,
        domain_idx: int | Sequence[int] | None = None,
    ) -> None:
        """Set the initial state of the environment.

        Parameters
        ----------
        randomize: bool | None
            Whether to randomize the initial state. If None, the default behavior is
            used.

        domain_idx: int | Sequence[int] | None
            Index of the initial domain to load, one for all environments or one per
            environment. Takes precedence over the random draw, so a randomized
            initial state can still start from a fixed domain. If None, a random
            index is used when randomizing and the first initial domain otherwise.
            Defaults to None.
        """
        self._sim = None  # type: ignore
        self._domain = None  # type: ignore
        gc.collect()
        torch.cuda.empty_cache()

        if randomize is None:
            randomize = self._randomize_initial_state

        if self.__load_domain_on_reset:
            idxs = self._initial_domain_indices(randomize, domain_idx)
            try:
                self._domain = self._load_initial_domains(mode=self.mode, idxs=idxs)
            except FileNotFoundError as err:
                raise RuntimeError(
                    "Initial domain not found. Please ensure it was downloaded."
                ) from err
            episodes: list[pd.DataFrame | None] = []
            for idx in idxs:
                try:
                    episodes.append(
                        self._load_uncontrolled_episode(idx=idx, mode=self.mode)
                    )
                except FileNotFoundError:
                    self._logger.warning(
                        "Uncontrolled episode data not found for domain %d in mode %s.",
                        idx,
                        self.mode.value,
                    )
                    episodes.append(None)
            self._uncontrolled_episodes = episodes
        else:
            self._domain = self._batch_domain(self._get_domain())
            self._uncontrolled_episodes = [None] * self._n_envs

        hooks = self._get_hooks(self._domain)
        self._sim = self._build_simulation(self._domain, hooks)

        # Some envs may need additional initialization
        self._additional_initialization()

        if randomize:
            with torch.no_grad():
                self._randomize_domain()

    @abstractmethod
    def _get_render_data(
        self,
        render_3d: bool,
        output_path: Path | None = None,
    ) -> dict[str, np.ndarray]:
        """Return data required for rendering.

        Parameters
        ----------
        render_3d: bool
            Whether to enable 3d rendering.

        output_path: Path | None
            The output path to save the rendered files. If None, saves to the current
            directory. Defaults to None.

        Returns
        -------
        dict[str, np.ndarray]
            A dictionary mapping slices to data arrays for rendering.
        """
        raise NotImplementedError

    @property
    def _resampler(self) -> MultiblockResampler:
        """Interpolating resampler for the blocks of this domain.

        Built lazily and cached: it only depends on the grid, which does not
        change over the lifetime of the environment.
        """
        if self.__resampler is None:
            self.__resampler = MultiblockResampler(
                vertex_coord_list=self._domain.getVertexCoordinates(),
                render_shape=self.render_shape[: self._ndims],
                fill_value=0.0,
            )

        return self.__resampler

    def _resample_is_differentiated(self) -> bool:
        """Whether a resample issued right now should record a graph.

        Mirrors ``Simulation._solve_is_differentiated``. Rendering and
        ``collect_statistics`` run under ``no_grad``, so they keep the compiled
        kernel and pay nothing for this.
        """
        return self._differentiable and torch.is_grad_enabled()

    def _diff_resampler(self, out_indices: torch.Tensor | None = None):
        """Cached differentiable resampler, optionally restricted to some cells.

        The compiled kernel has no autograd support, so everything downstream of
        it is detached; this is the pure-torch equivalent, which is not.

        The resample is a fixed linear map (all the masks are geometry), so the
        operator is built once, and ``out_indices`` keeps only the rows for the
        cells actually read. That restriction is exact. It also matters: a few hundred
        sensors need only a small fraction of the operator and tape of the full
        grid.
        """
        from phipict.grid.resample import DiffMultiblockResampler

        coords = self._sim.output_resampling_coords
        out_shape = self._sim.output_resampling_shape
        fill_max_steps = self._sim.output_resampling_fill_max_steps
        dtype = self._domain.getBlocks()[0].velocity.dtype

        # `output_resampling_coords` falls through to `domain.getVertexCoordinates()`,
        # which hands back a fresh list of fresh tensor objects on every call, so
        # `id()` is no identity for the grid: the lookup missed every time and the
        # operator was rebuilt once per differentiated observation. A full weight
        # assembly inside every replayed backward step. The key below is the geometry
        # itself, and the entry holds the tensors it was built from, so the storage
        # behind an address cannot be freed and reallocated while an entry names it
        # (which is the way a `data_ptr` key goes stale and silently serves the wrong
        # operator)
        grid_key = (
            None
            if coords is None
            else tuple((t.data_ptr(), tuple(t.shape), t.dtype) for t in coords)
        )
        out_key = (
            None
            if out_indices is None
            else (out_indices.data_ptr(), tuple(out_indices.shape), out_indices.dtype)
        )
        shape_key = None if out_shape is None else tuple(out_shape)
        key = (grid_key, out_key, shape_key, fill_max_steps, dtype)

        cached = self.__diff_resamplers.get(key)
        if cached is not None:
            return cached[1]

        resampler = DiffMultiblockResampler(
            coords_list=coords,
            out_shape=out_shape,
            dtype=dtype,
            fill_max_steps=fill_max_steps,
            out_indices=out_indices,
        )
        # Keep only the operators for the current grid, so `set_state` cannot
        # accumulate one hierarchy per rebuild. This also releases the previous
        # grid's coordinates, which the dropped entries were keeping alive
        self.__diff_resamplers = {
            k: v for k, v in self.__diff_resamplers.items() if k[0] == grid_key
        }
        keep_alive = (
            list(coords or ())
            if out_indices is None
            else [*(coords or ()), out_indices]
        )
        self.__diff_resamplers[key] = (keep_alive, resampler)
        return resampler

    def _fold_envs(
        self, data_list: list[torch.Tensor]
    ) -> tuple[list[torch.Tensor], int]:
        """Fold the env dim of per-block data into the channels, for the samplers.

        The samplers resample ``[1, C, ...]`` data with any number of channels, so
        ``[E, C, ...]`` is resampled as ``[1, E * C, ...]`` in one call. Data shared
        by all environments (``[1, C, ...]``) is broadcast first.
        """
        n_envs = max(data.size(0) for data in data_list)
        if n_envs == 1:
            return data_list, 1
        folded = []
        for data in data_list:
            if data.size(0) != n_envs:
                data = data.expand(n_envs, *data.shape[1:])
            folded.append(data.reshape(1, -1, *data.shape[2:]))
        return folded, n_envs

    def _resample_blocks(self, data_list: list[torch.Tensor]) -> torch.Tensor:
        """Resample per-block cell data onto the uniform output grid.

        This is the sampler behind :meth:`get_velocity`, :meth:`get_pressure` and
        :meth:`get_vorticity`, and hence behind the observations. For rendering,
        prefer :meth:`_render_plane`, which interpolates and is free of the block
        artifacts of this sampler.

        On a differentiable environment with grad enabled this routes to the
        pure-torch resampler, so the observation stays connected to the action;
        otherwise it uses the compiled kernel, which detaches.

        Parameters
        ----------
        data_list: list[torch.Tensor]
            Per-block cell data, one entry per block of the domain.

        Returns
        -------
        torch.Tensor
            The resampled data of shape [E, C, Y, X] for 2D or [E, C, Z, Y, X] for
            3D, with E the number of environments.
        """
        folded, n_envs = self._fold_envs(data_list)
        if self._resample_is_differentiated():
            out = self._diff_resampler()(folded)
        else:
            assert self._sim.output_resampling_coords is not None
            assert self._sim.output_resampling_shape is not None

            out = _resample_block_data(
                data_list=folded,
                vertex_coord_list=self._sim.output_resampling_coords,
                resampling_out_shape=self._sim.output_resampling_shape,
                ndims=self._ndims,
                fill_max_steps=self._sim.output_resampling_fill_max_steps,
            )
        return out.reshape(n_envs, -1, *out.shape[2:])

    def _resample_blocks_at(
        self, data_list: list[torch.Tensor], out_indices: torch.Tensor
    ) -> torch.Tensor:
        """Resample per-block data straight to selected output cells.

        For point-sensor observations: same values as resampling the whole grid
        and indexing it, at ~1e-4 of the cost. ``out_indices`` is a flat index or
        a ``[dims, R]`` tensor of per-axis ``(x, y[, z])`` indices; results come
        back as ``[E, C, R]`` in the order given, with E the number of
        environments.
        """
        if self._resample_is_differentiated():
            folded, n_envs = self._fold_envs(data_list)
            out = self._diff_resampler(out_indices)(folded)
            return out.reshape(n_envs, -1, out.size(-1))

        full = self._resample_blocks(data_list)
        if out_indices.dim() == 2:
            idx = [out_indices[d].long() for d in range(out_indices.size(0))]
            # out_indices rows are (x, y[, z]); the grid is [..., z, y, x]
            return full[(slice(None), slice(None), *reversed(idx))]
        return full.reshape(full.size(0), full.size(1), -1)[:, :, out_indices.long()]

    def _render_plane(
        self,
        data_list: list[torch.Tensor],
        axis: str | None = None,
        index: int | None = None,
        mirror: Sequence[str] | None = None,
    ) -> np.ndarray:
        """Resample per-block cell data onto a uniform 2D plane, for rendering.

        The blocks are interpolated over the cell centers of all blocks at once,
        which is continuous across block interfaces and avoids the artifacts the
        PICT sampler introduces there. A 2D domain is resampled as a whole; of a
        3D domain a single plane is resampled, which costs no more than a 2D
        domain and avoids resampling the full volume.

        This detaches the data from the graph, so it is for rendering only. Use
        :meth:`_resample_blocks` for anything that feeds observations or needs to
        stay differentiable.

        Parameters
        ----------
        data_list: list[torch.Tensor]
            Per-block cell data, one entry per block of the domain.

        axis: str | None
            The axis to slice a 3D domain along, "x", "y" or "z". Must be None
            for a 2D domain. Defaults to None.

        index: int | None
            The index of the plane along ``axis`` of the render grid. If None,
            the middle of that axis is used. Defaults to None.

        mirror: Sequence[str] | None
            The axes ("x", "y", "z") to mirror the plane along. Axes that do not
            span the plane are ignored, so the same set of axes can be passed for
            every slice. If None, :attr:`_render_mirror_axes` is used. Defaults
            to None.

        Returns
        -------
        np.ndarray
            The plane of shape (H, W) for single-channel data, else (C, H, W).
        """
        data_list = [self._render_env_data(data) for data in data_list]
        if self._ndims == 2:
            if axis is not None:
                raise ValueError("A 2D domain has no slice axis")

            plane = self._resampler(data_list)
        elif axis is None:
            raise ValueError("Slicing a 3D domain needs an axis: 'x', 'y' or 'z'")
        else:
            plane = self._resampler.extract_slice(data_list, axis=axis, index=index)

        return self._mirror_plane(plane, axis=axis, mirror=mirror)

    def _render_env_data(self, data: torch.Tensor) -> torch.Tensor:
        """The data of the environment being rendered, see :meth:`render`.

        Per-environment block data ``[E, C, ...]`` is reduced to ``[1, C, ...]``;
        anything else (shared data, or data already of one environment) is
        returned as is.
        """
        if torch.is_tensor(data) and data.dim() == self._ndims + 2 and data.size(0) > 1:
            return data[self._render_env_idx : self._render_env_idx + 1]
        return data

    def _mirror_plane(
        self,
        plane: np.ndarray,
        axis: str | None,
        mirror: Sequence[str] | None,
    ) -> np.ndarray:
        """Mirror a rendered plane along the requested axes.

        See :meth:`_render_plane`.
        """
        mirror_axes = self._render_mirror_axes if mirror is None else tuple(mirror)
        if not mirror_axes:
            return plane

        invalid = set(mirror_axes) - {"x", "y", "z"}
        if invalid:
            raise ValueError(
                f"Invalid mirror axes {sorted(invalid)}, expected 'x', 'y' or 'z'"
            )

        # The plane is (vertical, horizontal), possibly with a leading channel
        # axis, so its axes are the last two either way
        plane_axes = slice_plane_axes(axis)
        flip_axes = tuple(
            plane_axes.index(name) - 2 for name in mirror_axes if name in plane_axes
        )
        if not flip_axes:
            return plane

        return np.flip(plane, axis=flip_axes)

    def _vorticity_blocks(self) -> list[torch.Tensor]:
        """Return the per-block vorticity, before any resampling.

        Returns
        -------
        list[torch.Tensor]
            One entry per block, of shape [E, 1, Y, X] in 2D or [E, 3, Z, Y, X]
            in 3D, with E the number of environments.
        """
        self._domain.UpdateDomainData()
        gradients = _C.ComputeSpatialVelocityGradients(self._domain)

        # gradients[block][k] is the gradient of the k'th velocity component,
        # with the channel axis holding the spatial direction: grad_u[:, i] = du/dx_i
        vorticity_blocks = []
        for block_id in range(len(gradients)):
            if self._ndims == 2:
                grad_u, grad_v = gradients[block_id]

                du_dy = grad_u[:, 1, :, :]
                dv_dx = grad_v[:, 0, :, :]

                vorticity_block = (dv_dx - du_dy).unsqueeze(1)
            else:
                grad_u, grad_v, grad_w = gradients[block_id]

                du_dy = grad_u[:, 1, :, :]
                dv_dx = grad_v[:, 0, :, :]

                dw_dx = grad_w[:, 0, :, :]
                du_dz = grad_u[:, 2, :, :]

                dv_dz = grad_v[:, 2, :, :]
                dw_dy = grad_w[:, 1, :, :]

                vorticity_block = torch.stack(
                    [
                        dw_dy - dv_dz,
                        du_dz - dw_dx,
                        dv_dx - du_dy,
                    ],
                    dim=1,
                )

            vorticity_blocks += [vorticity_block]

        return vorticity_blocks

    def _squeeze_fields(self, fields: torch.Tensor) -> torch.Tensor:
        """Drop the singleton dims of resampled fields ``[E, C, ...]``.

        A single environment loses every singleton dim, as before batching
        existed; a vectorized environment keeps its env dim.
        """
        if not self._vectorized:
            return fields.squeeze()
        return fields.reshape(fields.size(0), *fields[0].squeeze().shape)

    def _vorticity_fields(self) -> torch.Tensor:
        """The resampled vorticity of every environment, ``[E, C, *spatial]``.

        The per-environment form the env implementations work with; environments
        that mask regions (e.g. a solid body) override this, and the public
        :meth:`get_vorticity` follows.
        """
        return self._resample_blocks(self._vorticity_blocks())

    def _velocity_fields(self) -> torch.Tensor:
        """The resampled velocity of every environment, ``[E, C, *spatial]``."""
        return self._resample_blocks(
            [block.velocity for block in self._domain.getBlocks()]
        )

    def _pressure_fields(self) -> torch.Tensor:
        """The resampled pressure of every environment, ``[E, 1, *spatial]``."""
        return self._resample_blocks(
            [block.pressure for block in self._domain.getBlocks()]
        )

    def _render_env_field(self, fields: torch.Tensor) -> torch.Tensor:
        """The field ``[C, *spatial]`` of the environment being rendered."""
        return fields[self._render_env_idx]

    def get_vorticity(
        self,
    ) -> torch.Tensor:
        """Get the vorticity field of the fluid.

        Returns
        -------
        torch.Tensor
            The vorticity field as a tensor, with a leading env dim for a
            vectorized environment.
        """
        return self._squeeze_fields(self._vorticity_fields())

    def get_velocity(
        self,
    ) -> torch.Tensor:
        """Get the velocity field of the fluid.

        Returns
        -------
        torch.Tensor
            The velocity field as a tensor, with a leading env dim for a
            vectorized environment.
        """
        return self._squeeze_fields(self._velocity_fields())

    def get_pressure(
        self,
    ) -> torch.Tensor:
        """Get the pressure field of the fluid.

        Returns
        -------
        torch.Tensor
            The pressure field as a tensor of shape (H, W) for 2D or (D, H, W) for
            3D, with a leading env dim for a vectorized environment.
        """
        return self._squeeze_fields(self._pressure_fields())

    @staticmethod
    def _format_render_data(
        data: np.ndarray,
        v_min: float | None = None,
        v_max: float | None = None,
        cmap: str = "viridis",
    ) -> np.ndarray:
        """Format data for rendering.
        This method normalizes the data and applies a colormap.

        Parameters
        ----------
        data: np.ndarray
            The data to be formatted.

        v_min: float | None
            The minimum value for normalization. If None, the minimum of the data is
            used.

        v_max: float | None
            The maximum value for normalization. If None, the maximum of the data is
            used.

        cmap: str
            The colormap to be applied.

        Returns
        -------
        np.ndarray
            The formatted data ready for rendering.
        """
        _v_min = np.min(data) if v_min is None else v_min
        _v_max = np.max(data) if v_max is None else v_max

        data = np.flip(data, axis=1)
        data = (data - _v_min) / (_v_max - _v_min)
        data = np.clip(data, 0.0, 1.0)
        return sns.color_palette(cmap, as_cmap=True)(data, bytes=True)[:, :, :3]

    def step(
        self, action: torch.Tensor
    ) -> tuple[
        dict[str, torch.Tensor],
        torch.Tensor,
        bool | torch.Tensor,
        bool | torch.Tensor,
        dict[str, torch.Tensor],
    ]:
        """Run one timestep of the environment's dynamics using the agent actions.

        When the end of an episode is reached (``terminated or truncated``), it is
        necessary to call :meth:`reset` to reset this environment's state for the next
        episode.

        Parameters
        ----------
        action: torch.Tensor
            The action to take, ``[n_envs, ...]`` for a vectorized environment.

        Returns
        -------
        tuple[
        dict[str, torch.Tensor], torch.Tensor, bool, bool, dict[str, torch.Tensor]]
            A tuple containing the observation, reward, terminated flag, truncated flag,
            and info dictionary. For a vectorized environment everything has a
            leading env dim, and the flags are bool tensors of shape ``[n_envs]``.
        """
        if not self._reset_called:
            raise RuntimeError(
                "Environment must be reset before stepping. Call 'reset()' before"
                "'step()'."
            )

        if not action.shape == self._zero_action.shape:
            raise ValueError(
                f"Action shape {action.shape} does not match expected shape "
                f"{self._zero_action.shape}."
            )

        # Policies usually act in float32; the boundary setters require the
        # domain dtype. The cast is differentiable, so the gradient reaches the
        # policy in its own dtype
        action = self._to_batched(action.to(dtype=self._dtype))

        step_fn = self._step_marl_impl if self._use_marl else self._step_impl
        if self._bptt_checkpoint and self._differentiable:
            if self._bptt_segment_size:
                obs, reward, terminated, info = self._segmented_step(action)
            else:
                obs, reward, terminated, info = self._checkpointed_step(action, step_fn)
        else:
            obs, reward, terminated, info = step_fn(action)

        self._n_steps += 1
        truncated = self._n_steps >= self._episode_length

        info = {k: v.detach() for k, v in info.items()}

        if self._vectorized:
            # All environments share the episode: they are truncated together, and
            # an environment cannot terminate on its own
            flags = torch.ones(self._n_envs, dtype=torch.bool, device=self._cuda_device)
            return (
                obs,
                reward,
                flags & bool(terminated),
                flags & truncated,
                info,
            )
        return (
            self._from_batched(obs),
            self._from_batched(reward),
            terminated,
            truncated,
            self._from_batched(info),
        )

    def _step_impl(
        self, action: torch.Tensor
    ) -> tuple[dict[str, torch.Tensor], torch.Tensor, bool, dict[str, torch.Tensor]]:
        """One environment step: advance the simulation, then close the step off.

        The step is split at the seam checkpointing needs it split at, so an env
        only implements the two halves: :meth:`_advance_impl` and
        :meth:`_finish_step`. Every env is cuttable into sub-step checkpoint
        segments by construction. Whether it is actually cut is
        ``bptt_segment_size``, which each env defaults for itself.

        Parameters
        ----------
        action: torch.Tensor
            The action to take.

        Returns
        -------
        tuple[dict[str, torch.Tensor], torch.Tensor, bool, dict[str, torch.Tensor]]
            A tuple containing the observation, reward, terminated flag, and info
            dictionary.
        """
        return self._finish_step(self._advance_impl(action, self._n_sim_steps))

    @abstractmethod
    def _advance_impl(
        self, action: torch.Tensor, n_sim_steps: int
    ) -> dict[str, torch.Tensor]:
        """Advance the simulation by ``n_sim_steps`` PISO steps.

        Parameters
        ----------
        action: torch.Tensor
            The action to take.
        n_sim_steps: int
            Number of PISO steps to run, which is a segment of an env step rather
            than necessarily the whole of one.

        Returns
        -------
        dict[str, torch.Tensor]
            Per-substep metrics, each with ``n_sim_steps`` entries along dim 0.
        """
        raise NotImplementedError

    @abstractmethod
    def _finish_step(
        self, metrics: dict[str, torch.Tensor]
    ) -> tuple[dict[str, torch.Tensor], torch.Tensor, bool, dict[str, torch.Tensor]]:
        """Close one env step off the per-substep metrics of all of its segments.

        Runs once per env step, outside any checkpoint segment, on the state the
        last segment left in the domain, which is still connected to the graph,
        so an observation taken here is differentiable.

        Parameters
        ----------
        metrics: dict[str, torch.Tensor]
            Per-substep metrics of the whole env step, as returned by
            :meth:`_advance_impl` and concatenated over its segments.

        Returns
        -------
        tuple[dict[str, torch.Tensor], torch.Tensor, bool, dict[str, torch.Tensor]]
            A tuple containing the observation, reward, terminated flag, and info
            dictionary.
        """
        raise NotImplementedError

    def _step_marl_impl(
        self, action: torch.Tensor
    ) -> tuple[dict[str, torch.Tensor], torch.Tensor, bool, dict[str, torch.Tensor]]:
        """One multi-agent environment step, split like the single-agent one.

        The agents act on the simulation through the action they are handed, so the
        advancing half is the same :meth:`_advance_impl`. Only the closing half
        differs, in that it hands back per-agent observations and rewards. An env
        therefore implements :meth:`_finish_marl_step` and gets the same sub-step
        checkpoint segments the single-agent step has.

        Parameters
        ----------
        action: torch.Tensor
            The individual agent actions.

        Returns
        -------
        tuple[dict[str, torch.Tensor], torch.Tensor, bool, dict[str, torch.Tensor]]
            A tuple containing the local observations, local rewards, a global
            terminated flag, and a global info dictionary.
        """
        return self._finish_marl_step(self._advance_impl(action, self._n_sim_steps))

    def _finish_marl_step(
        self, metrics: dict[str, torch.Tensor]
    ) -> tuple[dict[str, torch.Tensor], torch.Tensor, bool, dict[str, torch.Tensor]]:
        """Close one env step off per agent, the multi-agent :meth:`_finish_step`.

        Runs under the same conditions as :meth:`_finish_step`: once per env step,
        outside any checkpoint segment, on the state the last segment left. It is
        implemented by every env that sets ``_supports_marl``.

        Parameters
        ----------
        metrics: dict[str, torch.Tensor]
            Per-substep metrics of the whole env step, as returned by
            :meth:`_advance_impl` and concatenated over its segments.

        Returns
        -------
        tuple[dict[str, torch.Tensor], torch.Tensor, bool, dict[str, torch.Tensor]]
            A tuple containing the local observations, local rewards, a global
            terminated flag, and a global info dictionary.
        """
        raise NotImplementedError

    @property
    def _n_sim_steps(self) -> int:
        """The number of simulation steps per environment step."""
        return max(1, int(self._step_length / self._dt))

    def seed(self, seed: int) -> None:
        """Update the random seeds and seed the random number generators.

        Parameters
        ----------
        seed: int
            The seed to set. If None, the current seed is used.
        """
        if seed is None:
            raise ValueError("Seed cannot be None.")

        self._seed = seed
        self._torch_rng_cuda = torch.Generator(device=self._cuda_device).manual_seed(
            seed
        )
        self._torch_rng_cpu = torch.Generator(device=self._cpu_device).manual_seed(seed)
        self._np_rng = np.random.default_rng(seed)

    def reset(
        self,
        seed: int | None = None,
        randomize: bool | None = None,
        domain_idx: int | Sequence[int] | None = None,
    ) -> tuple[dict[str, torch.Tensor], dict[str, torch.Tensor]]:
        """Resets the environment to an initial internal state, returning an initial
        observation and info.

        Parameters
        ----------
        seed: int | None
            The seed to use for random number generation. If None, the current seed is
            used.

        randomize: bool | None
            Whether to randomize the initial state. If None, the default behavior is
            used.

        domain_idx: int | Sequence[int] | None
            Index of the initial domain to load, one for all environments or one per
            environment. Takes precedence over the random draw, so a randomized
            initial state can still start from a fixed domain. If None, every
            environment draws a random index when randomizing, and all start from
            the first initial domain otherwise. Defaults to None.

        Returns
        -------
        tuple[dict[str, torch.Tensor], dict[str, torch.Tensor]]
            A tuple containing the initial observation and an info dictionary.
            The observation has a leading env dim for a vectorized environment.
        """
        # First, we update the random seed as it may affect the initial state
        if seed is None:
            if self._seed is None:
                raise ValueError(
                    "Seed must be provided either during reset or by calling seed()."
                )
        else:
            self.seed(seed)

        # Then, we re-initialize the environment
        self._set_initial_state(randomize=randomize, domain_idx=domain_idx)

        # Drop the pressure warm-start guesses. They cannot change a converged
        # answer, but they change iteration counts and therefore round-off, so
        # carrying them across an episode boundary would make two episodes from
        # the same initial state depend on whatever ran before them
        self._sim.clear_pressure_guess()

        self._reset_called = True
        self._n_steps = 0
        self._n_episodes += 1

        self._apply_action(self._batched_zero_action)

        if self._use_marl:
            obs = self._get_local_obs()
        else:
            obs = self._get_global_obs()

        info: dict[str, torch.Tensor] = {}
        return self._from_batched(obs), info

    def render(
        self,
        save: bool = False,
        render_3d: bool = False,
        filename: str | None = None,
        output_path: Path | None = None,
        env_ids: int | Sequence[int] | None = None,
    ) -> np.ndarray:
        """Render the current state of the environment.

        Parameters
        ----------
        save: bool
            Whether to save the rendered frame as a PNG file. Defaults to False.

        render_3d: bool
            Whether to enable 3d rendering. Defaults to False.

        filename: str | None
            The filename of the saved PNG files. If None, a default name is used.
            Defaults to None.

        output_path: Path | None
            The output path to save the rendered files. If None, saves to the current
            directory. Defaults to None.

        env_ids: int | Sequence[int] | None
            The environments of a vectorized environment to render: one index for a
            single frame, a sequence for a stack of frames, None (the default) for
            all environments. Must be None for a single environment.

        Returns
        -------
        np.ndarray
            The rendered frame ``[H, W, 3]`` for a single environment (or a single
            ``env_ids`` index), else the frames ``[len(env_ids), H, W, 3]`` of the
            requested environments matching the layout of vectorized-env video
            recorders.
        """
        if env_ids is not None and not self._vectorized:
            raise ValueError("env_ids is only supported for a vectorized environment.")

        if not self._vectorized:
            ids, single = [0], True
        elif env_ids is None:
            ids, single = list(range(self._n_envs)), False
        elif isinstance(env_ids, (int, np.integer)):
            ids, single = [int(env_ids)], True
        else:
            ids, single = [int(i) for i in env_ids], False

        for env_idx in ids:
            if not 0 <= env_idx < self._n_envs:
                raise ValueError(
                    f"env_ids {env_idx} out of range for {self._n_envs} environments."
                )

        output_path = output_path or Path(".")
        output_path.mkdir(parents=True, exist_ok=True)

        frames = [
            self._render_env(env_idx, save, render_3d, filename, output_path)
            for env_idx in ids
        ]
        return frames[0] if single else np.stack(frames)

    def _render_env(
        self,
        env_idx: int,
        save: bool,
        render_3d: bool,
        filename: str | None,
        output_path: Path,
    ) -> np.ndarray:
        """Render one environment, see :meth:`render`."""
        from PIL import Image

        self._render_env_idx = env_idx
        try:
            render_data = self._get_render_data(
                render_3d=render_3d,
                output_path=output_path if save else None,
            )
        finally:
            self._render_env_idx = 0

        if save:
            # the frames of every environment of a vectorized env are kept apart
            suffix = (
                f"_env{env_idx + self._env_index_offset}" if self._vectorized else ""
            )
            for slice_name, data in render_data.items():
                img = Image.fromarray(data)
                if filename is not None:
                    img.save(output_path / f"{slice_name}{suffix}_{filename}.png")
                else:
                    img.save(
                        output_path
                        / f"{slice_name}{suffix}_{self._n_episodes}_{self._n_steps}.png"
                    )

        if self._default_render_key in render_data:
            return render_data[self._default_render_key]
        else:
            # Return the first slice's data as a numpy array
            return next(iter(render_data.values()))

    @abstractmethod
    def plot(self, output_path: Path | None = None) -> None:
        """Plot the environments configuration.

        Parameters
        ----------
        output_path: Path | None
            Path to save the plot. If None, the current directory is used. Defaults to
            None.
        """
        raise NotImplementedError

    @property
    @abstractmethod
    def id(self) -> str:
        """Unique identifier for the environment."""
        raise NotImplementedError

    @property
    @abstractmethod
    def initial_domain_id(self) -> str:
        """Unique identifier for the initial domain."""
        raise NotImplementedError

    def _get_domain_dir(self, idx: int) -> Path:
        return fluidgym_config.initial_domains_path / self.initial_domain_id / str(idx)

    def _save_initial_domain(self, mode: EnvMode, idx: int) -> None:
        """Save the initial domain to disk.

        Parameters
        ----------
        mode : EnvMode
            Environment mode ('train', 'val', 'test').

        idx: int
            Index of the initial domain to save.
        """
        out_dir = self._get_domain_dir(idx)
        out_dir.mkdir(parents=True, exist_ok=True)
        save_domain(
            domain=self._domain,
            path=out_dir / mode.value,
        )

    def load_domain(self, path: Path) -> None:
        """Load a domain from disk given a path and set it as the environment's current
        domain.

        Parameters
        ----------
        path: Path
            Path to the domain.
        """
        self._domain = load_domain(
            path=path,
            dtype=self._dtype,
            device=self._cuda_device,
            with_scalar=True,
        )
        self._domain.PrepareSolve()
        # every environment of a vectorized env starts from the loaded state
        self._domain = self._batch_domain(self._domain)
        hooks = self._get_hooks(self._domain)
        self._sim = self._build_simulation(self._domain, hooks)

        # Some envs may need additional initialization
        self._additional_initialization()

    def load_initial_domain(self, idx: int, mode: EnvMode | None = None) -> None:
        """Load an initial domain from disk and set it as the environments current
        domain.

        Parameters
        ----------
        idx: int
            Index of the initial domain to load.

        mode: EnvMode | None
            Environment mode ('train', 'val', 'test'). If None, uses the current mode.
            Defaults to None.
        """
        if mode is None:
            mode = self._mode

        out_dir = self._get_domain_dir(idx)
        self.load_domain(out_dir / mode.value)

    def _load_initial_domain(self, mode: EnvMode, idx: int) -> _C.Domain:
        """Load an initial domain from disk.

        Parameters
        ----------
        mode: EnvMode
            Environment mode ('train', 'val', 'test').

        idx: int
            Index of the initial domain to load.

        Returns
        -------
        _C.Domain
            The loaded domain.
        """
        out_dir = self._get_domain_dir(idx)
        domain = load_domain(
            path=out_dir / mode.value,
            dtype=self._dtype,
            device=self._cuda_device,
            with_scalar=True,
        )
        domain.PrepareSolve()
        return domain

    def init(self, domain_idxs: list[int] | None = None) -> None:
        """Generate and save the initial domain if it does not already exist.

        Parameters
        ----------
        domain_idxs: list[int]
            List of domain indices to initialize. If empty, initializes all domains.
            Defaults to None.
        """
        if self._vectorized:
            raise RuntimeError(
                "Initial domains are generated by a single environment; construct the "
                "env without n_envs to run init()."
            )
        self._enable_actions = False
        self.__load_domain_on_reset = False

        def save_render(mode: EnvMode, idx: int) -> None:
            self.render(
                save=True,
                filename=f"{mode.value}",
                output_path=fluidgym_config.initial_domains_path
                / self.initial_domain_id
                / str(idx),
            )

        if domain_idxs is None:
            domain_idxs = list(range(N_INITIAL_DOMAINS))

        for i in domain_idxs:
            self._logger.info(f"Generating initial domains {i}")
            for mode_seed, mode in zip(
                MODE_SEEDS,
                [EnvMode.TRAIN, EnvMode.VAL, EnvMode.TEST],
                strict=False,
            ):
                if self._check_initial_domains_exists(mode=mode, idx=i):
                    self._logger.info(
                        f"Initial domain for {mode} with index {i} already exists."
                        f"Skipping generation."
                    )
                    self.load_initial_domain(idx=i, mode=mode)
                    save_render(mode=mode, idx=i)
                    continue

                seed = mode_seed + i

                self.reset(seed=seed)
                self._logger.info(f"Simulating {mode} domain.")

                # For additional randomization, we adapt the number of steps
                n_steps = self._initial_domain_steps + self._np_rng.integers(
                    -int(0.15 * self._initial_domain_steps),
                    int(0.15 * self._initial_domain_steps) + 1,
                )

                for _ in range(n_steps):
                    self.step(self._zero_action)

                    # DEBUG
                    self.render(save=True)

                self._save_initial_domain(mode=mode, idx=i)
                save_render(mode=mode, idx=i)
                self._logger.info(f"Finished simulating {mode} domain.")

                # For some fields (e.g. the cylinder), we generate the domains
                # by continuing the simulation, so we only need to do this once
                if not self._initial_domain_restart:
                    # Validation
                    for _ in range(int(n_steps * 0.1)):
                        self.step(self._zero_action)
                    self._save_initial_domain(mode=EnvMode.VAL, idx=i)
                    save_render(mode=EnvMode.VAL, idx=i)
                    self._logger.info("Finished simulating val domain.")

                    # Test
                    for _ in range(int(n_steps * 0.1)):
                        self.step(self._zero_action)
                    self._save_initial_domain(mode=EnvMode.TEST, idx=i)
                    save_render(mode=EnvMode.TEST, idx=i)
                    self._logger.info("Finished simulating test domain.")
                    break

        self._enable_actions = True
        self.__load_domain_on_reset = True

    def _save_domain_statistics(self, statistics: dict[str, dict[str, float]]) -> None:
        """Save statistics as a JSON file.

        Parameters
        ----------
        statistics: dict
            The statistics to save.
        """
        save_statistics(
            path=fluidgym_config.initial_domains_path / self.initial_domain_id,
            data=statistics,
        )

    def _load_domain_statistics(self) -> dict[str, dict[str, float]]:
        """Load statistics from a JSON file.

        Returns
        -------
        dict[str, dict[str, float]]
            The loaded statistics.
        """
        stats = load_statistics(
            path=fluidgym_config.initial_domains_path / self.initial_domain_id,
        )

        self._velocity_stats = Stats(**stats["velocity_magnitude"])
        self._pressure_stats = Stats(**stats["pressure"])

        # A metric added since the statistics on disk were last written is simply
        # absent, and an env that normalises by it is expected to fall back rather
        # than fail to construct, otherwise the statistics could never be
        # regenerated for it
        self._metrics_stats = {
            key: Stats(**stats[key]) for key in self._metrics if key in stats
        }
        missing = [key for key in self._metrics if key not in stats]
        if missing:
            self._logger.warning(
                f"Domain statistics carry no entry for {missing}; re-run "
                f"collect_statistics.py to add them. Anything normalising by "
                f"these metrics falls back to its default until then."
            )

        return stats

    def _save_uncontrolled_episode(
        self, metrics: pd.DataFrame, idx: int, mode: EnvMode
    ) -> None:
        """Save metrics as a CSV file.

        Parameters
        ----------
        statistics: pd.DataFrame
            The metrics to save.

        idx: int
            Index of the initial domain.

        mode : EnvMode
            Environment mode ('train', 'val', 'test').
        """
        save_uncontrolled_episode(
            path=self._get_domain_dir(idx),
            mode_name=mode.value,
            episode_df=metrics,
        )

    def _load_uncontrolled_episode(self, idx: int, mode: EnvMode) -> pd.DataFrame:
        """Load uncontrolled episode metrics for a given initial domain.

        Parameters
        ----------
        idx: int
            Index of the initial domain.

        mode : EnvMode
            Environment mode ('train', 'val', 'test').

        Returns
        -------
        pd.DataFrame
            The loaded metrics.
        """
        return load_uncontrolled_episode(
            path=self._get_domain_dir(idx),
            mode_name=mode.value,
        )

    def get_uncontrolled_episode_metrics(
        self,
    ) -> pd.DataFrame | list[pd.DataFrame | None] | None:
        """Get the uncontrolled episode metrics for the current domain.

        Note: This method returns the metrics for the currently loaded
        (non-randomized) initial domain. If the environment has been reset
        with randomization, the metrics may not correspond to the current state.

        Returns
        -------
        pd.DataFrame | list[pd.DataFrame | None] | None
            The uncontrolled episode metrics, or None if not available. One entry
            per environment for a vectorized environment.
        """
        if self._vectorized:
            return list(self._uncontrolled_episodes)
        return self._uncontrolled_episodes[0] if self._uncontrolled_episodes else None

    def detach(self) -> None:
        """Detach all tensors in the simulation from the computation graph."""
        self._domain.Detach()

        assert self._domain.viscosity.grad_fn is None
        for b in self._domain.getBlocks():
            assert b.velocity.grad_fn is None
            assert b.velocityGrad.grad_fn is None
            assert b.pressure.grad_fn is None
            assert b.pressureGrad.grad_fn is None

    def plot_grid(self) -> None:
        """Plot the simulation grid."""
        if not hasattr(self, "_domain"):
            raise RuntimeError("Domain is not initialized. Please call reset() first.")

        grids: list[torch.Tensor] = self._domain.getVertexCoordinates()
        if self._ndims == 3:
            grids = [grid[:, :2, 0, :, :] for grid in grids]

        fig, ax = plot_grids(
            grids,
            color=DEFAULT_PALETTE[: len(grids)],  # type: ignore
            type="pdf",
            linewidth=0.5,
            fig_scale=2,
        )
        ax.grid(True)
        fig.savefig(f"{self.id}_grid.pdf")

    @property
    def action_space(self) -> spaces.Box:
        """The action space of the environment."""
        return self._action_space

    @property
    def observation_space(self) -> spaces.Dict:
        """The observation space of the environment."""
        return self._observation_space

    def get_state(self) -> EnvState:
        """Get the current state of the environment.

        Returns
        -------
        EnvState
            The current state of the environment.
        """
        domain = self._domain.Clone()
        domain.PrepareSolve()
        domain.Detach()

        return EnvState(
            class_name=self.__class__.__name__,
            domain=domain,
            n_steps=self._n_steps,
            mode=self._mode,
            additional_info={},
        )

    def set_state(self, state: EnvState) -> None:
        """Set the current state of the environment.

        Parameters
        ----------
        state: EnvState
            The state to set the environment to.
        """
        if state.class_name != self.__class__.__name__:
            raise ValueError(
                f"State class name {state.class_name} does not match "
                f"environment class name {self.__class__.__name__}."
            )

        self._domain = state.domain.Clone()
        self._domain.PrepareSolve()
        self._sim = self._build_simulation(
            domain=self._domain,
            hooks=self._get_hooks(self._domain),
        )
        self._n_steps = state.n_steps
        self._mode = state.mode

        self._additional_initialization()
