# @package _global_
defaults:
  - _self_
  - cluster: local

env_id: CylinderJet2D-easy-v0
env_kwargs: {}
eval_env_kwargs: {}
  
seed: 42

rl_mode: sarl

# DPC setup
total_timesteps: 5e4
horizon: 40
lr: 0.001                  
discount_factor: 0.999
max_grad_norm: 0.5

n_test_episodes: 10

wandb:
  enable: true
  entity: safe-autonomous-systems
  project: jbecktepe-fluidgym

hydra:
  output_subdir: "."
  run: 
    dir: output/training_dpc/${rl_mode}/${env_id}/DPC/${seed}
  sweep:
    dir: output/training_dpc/${rl_mode}/${env_id}/DPC/${seed}
    subdir: ""
  job:
    chdir: true